# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16L0k9sGWkvjS3GifMszhIFHcKRgGYlSR
"""

import pandas as pd
import csv
import plotly.graph_objects as go
df=pd.read_csv("data1.csv")
print(df.groupby("level")["attempt"].mean())

fig=go.Figure(go.Bar(
    x=df.groupby("level")["attempt"].mean(),
    y=["Level1","Level2","Level3","Level4"],
    orientation = "h"
))
fig.show()

import pandas as pd
import csv
import plotly.graph_objects as go